language:
  - scala
  - java
scala: 2.11
jdk: oraclejdk8
script:
  - gradle clean test run
  - sbt $TRAVIS_SCALA_VERSION clean test run
cache:
  directories:
    - $HOME/.gradle
    - .gradle
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2
    - project/target
